---
- name: install
  hosts: webservers
  become: true
  tasks:
  - name: install 
    yum:
     name: docker
     state: latest
    notify: restart docker

  handlers:
  - name: restart docker
    service:
     name: docker
     state: restarted



