---
- name: install
  hosts: webservers
  become: true
  tasks:
  - name: install "{{ pkg_name }}"
    yum: 
     name: "{{ pkg_name }}"
     state: latest

  - name: restart "{{ pkg_name }}"
    service:
     name: "{{ pkg_name }}"
     state: restarted
